<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #000;
        }

        h2 {
            text-align: center;
            margin-bottom: 5px;
        }

        .meta {
            text-align: center;
            margin-bottom: 20px;
            font-size: 11px;
        }

        .info {
            margin-bottom: 15px;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
        }

        th {
            background: #f2f2f2;
        }

        .section-title {
            margin-top: 20px;
            font-weight: bold;
            font-size: 14px;
        }
    </style>
</head>

<body>

    <!-- HEADER -->
    <h2>Kuya Benz Sales Report</h2>

    <div class="meta">
        Report Generated on: {{ $reportDate }}
    </div>

    <!-- INFO SECTION -->
    <div class="info">
        <p><strong>Generated By:</strong> {{ $generatedBy ?? 'System' }}</p>
        <p><strong>Filter:</strong> {{ $filter ?? 'All' }}</p>

        @if($selectedDate)
            <p><strong>Date Filter:</strong> {{ $selectedDate }}</p>
        @endif
    </div>

    <!-- SALES SUMMARY -->
    <div class="section-title">Sales Summary</div>

    <table>
        <thead>
            <tr>
                <th>Period</th>
                <th>Transactions</th>
                <th>Total Sales</th>
            </tr>
        </thead>

        <tbody>
            @foreach($salesData as $row)
            <tr>
                <td>{{ $row->date }}</td>
                <td>{{ $row->transactions }}</td>
                <td>₱{{ number_format($row->total_sales, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- ORDERS -->
    <div class="section-title">Recent Orders</div>

    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Cashier</th>
                <th>Total</th>
            </tr>
        </thead>

        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>#{{ $order->order_id }}</td>
                <td>{{ $order->user->username }}</td>
                <td>₱{{ number_format($order->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>